/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated/reportes'
import { Route as AuthenticatedProveedoresRouteImport } from './routes/_authenticated/proveedores'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedDemoRouteImport } from './routes/_authenticated/demo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedCasosIndexRouteImport } from './routes/_authenticated/casos.index'
import { Route as AuthenticatedCasosIdRouteImport } from './routes/_authenticated/casos.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProveedoresRoute =
  AuthenticatedProveedoresRouteImport.update({
    id: '/proveedores',
    path: '/proveedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoRoute = AuthenticatedDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCasosIndexRoute = AuthenticatedCasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCasosIdRoute = AuthenticatedCasosIdRouteImport.update({
  id: '/casos/$id',
  path: '/casos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AuthenticatedChatRoute
  '/config': typeof AuthenticatedConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/api/chat': typeof ApiChatRoute
  '/casos/$id': typeof AuthenticatedCasosIdRoute
  '/casos/': typeof AuthenticatedCasosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AuthenticatedChatRoute
  '/config': typeof AuthenticatedConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/proveedores': typeof AuthenticatedProveedoresRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/api/chat': typeof ApiChatRoute
  '/casos/$id': typeof AuthenticatedCasosIdRoute
  '/casos': typeof AuthenticatedCasosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demo': typeof AuthenticatedDemoRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/proveedores': typeof AuthenticatedProveedoresRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/casos/$id': typeof AuthenticatedCasosIdRoute
  '/_authenticated/casos/': typeof AuthenticatedCasosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chat'
    | '/config'
    | '/dashboard'
    | '/demo'
    | '/docs'
    | '/proveedores'
    | '/reportes'
    | '/api/chat'
    | '/casos/$id'
    | '/casos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/chat'
    | '/config'
    | '/dashboard'
    | '/demo'
    | '/docs'
    | '/proveedores'
    | '/reportes'
    | '/api/chat'
    | '/casos/$id'
    | '/casos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/chat'
    | '/_authenticated/config'
    | '/_authenticated/dashboard'
    | '/_authenticated/demo'
    | '/_authenticated/docs'
    | '/_authenticated/proveedores'
    | '/_authenticated/reportes'
    | '/api/chat'
    | '/_authenticated/casos/$id'
    | '/_authenticated/casos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proveedores': {
      id: '/_authenticated/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AuthenticatedProveedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/casos/': {
      id: '/_authenticated/casos/'
      path: '/casos'
      fullPath: '/casos/'
      preLoaderRoute: typeof AuthenticatedCasosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/casos/$id': {
      id: '/_authenticated/casos/$id'
      path: '/casos/$id'
      fullPath: '/casos/$id'
      preLoaderRoute: typeof AuthenticatedCasosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemoRoute: typeof AuthenticatedDemoRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedProveedoresRoute: typeof AuthenticatedProveedoresRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedCasosIdRoute: typeof AuthenticatedCasosIdRoute
  AuthenticatedCasosIndexRoute: typeof AuthenticatedCasosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemoRoute: AuthenticatedDemoRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedProveedoresRoute: AuthenticatedProveedoresRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedCasosIdRoute: AuthenticatedCasosIdRoute,
  AuthenticatedCasosIndexRoute: AuthenticatedCasosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
